language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

# command to install dependencies
install:
  - rm $VIRTUAL_ENV/lib/*/no-global-site-packages.txt
  - pip install --use-mirrors .

# command to run tests
script: py.test
